# Metade esquerda (central)

# Scroll suave do trackpad (HID resolution multiplier) — só na central
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Reportar ao host também a bateria da metade direita
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Sem trackpad físico deste lado
CONFIG_INPUT_TPS43=n
