# Metade esquerda (central) — com o trackpad TPS65 ligado

CONFIG_INPUT_TPS43=y
CONFIG_I2C=y

# Scroll suave do trackpad (HID resolution multiplier)
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Reportar ao host também a bateria da metade direita
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
